#pragma once
// Auto generated by get-version.sh
#include <mixins/std/c++types.h>

namespace Quark::System {
    constexpr u8          OsVersionMajor = 1;
    constexpr u8          OsVersionMinor = 0;
    constexpr const char* OsVersionPatchId = "22c0ba1";
}
