namespace Qk {
    enum KeyModifiers
    {
        KEY_MOD_ALT      = 1 << 0,
        KEY_MOD_CTRL     = 1 << 1,
        KEY_MOD_SHIFT    = 1 << 2,
        KEY_MOD_CAPSLOCK = 1 << 3,
    };

    enum KeyState
    {
        KEY_STATE_PRESSED,
        KEY_STATE_RELEASED,
    };

    enum class Key
    {
        None,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,
        PageScroll,
        ScrollLock,
        PauseBreak,
        NumberLock,
        Insert,
        Delete,
        Home,
        End,
        PageUp,
        PageDown,
        Escape,
        Tab,
        CapsLock,
        Space,
        Backspace,
        Enter,
        LShift,
        LCtrl,
        LAlt,
        RAlt,
        RCtrl,
        RShift,
        ArrowLeft,
        ArrowRight,
        ArrowUp,
        ArrowDown,
        Num0,
        Num1,
        Num2,
        Num3,
        Num4,
        Num5,
        Num6,
        Num7,
        Num8,
        Num9,
        A,
        B,
        C,
        D,
        E,
        F,
        G,
        H,
        I,
        J,
        K,
        L,
        M,
        N,
        O,
        P,
        Q,
        R,
        S,
        T,
        U,
        V,
        W,
        X,
        Y,
        Z,
        Numpad1,
        Numpad2,
        Numpad3,
        Numpad4,
        Numpad5,
        Numpad6,
        Numpad7,
        Numpad8,
        Numpad9,
        Numpad0,
        NumpadAdd,
        NumpadMinus,
        NumpadEnter,
        NumpadSlash,
        NumpadMultiply,
        NumpadPeriod,
        Exclamation /* ! */,
        DoubleQuote /* " */,
        Pound /* # */,
        Dollar /* $ */,
        Percentage /* % */,
        And /* & */,
        Quote /* ' */,
        LeftBracket /* ( */,
        RightBracket /* ) */,
        Multiply /* * */,
        Add /* + */,
        Comma /* , */,
        Minus /* - */,
        Period /* . */,
        Slash /* / */,
        Backtick /* ` */,
        Equals,
        Backslash,
        Colon,
        Semicolon,
        LessThan,
        GreaterThan,
        Question,
        At,
        Caret,
        Underline,
        Wave,
        LeftBrace,
        RightBrace,
        LeftMenu,
        RightMenu,
        PreviousTrack,
        NextTrack,
        Mute,
        MediaPlay,
        MediaStop,
        MediaSelect,
        VolumeDown,
        VolumeUp,
        Calculator,
        Apps,
        Email,
        Computer,
        CursorLeft,
        CursorRight,
        CursorUp,
        CursorDown,
        WebHome,
        WebRefresh,
        WebStop,
        WebSearch,
        WebForward,
        WebBackward,
        WebFavorites,
        Power,
        Sleep,
        Wake
    };
}