#!/bin/bash

SCRIPT_DIR=$(dirname "$(realpath "$0")")
VERSION_FILE="$SCRIPT_DIR/../Kernel/Include/quark/os/version.h"

if [ ! -f "$VERSION_FILE" ]; then 
    touch "$VERSION_FILE"
fi

VERSION_MAJOR=1
VERSION_MINOR=0
VERSION_PATCH=$(git rev-parse HEAD | cut -c1-7)

if [ -z "$VERSION_PATCH" ]; then
    echo "Failed to get version patch"
    VERSION_PATCH="unknown"
fi

echo $VERSION_MAJOR.$VERSION_MINOR.$VERSION_PATCH

cat << EOF > "$VERSION_FILE"
#pragma once
// Auto generated by get-version.sh
#include <mixins/std/c++types.h>
#include <mixins/std/string.h>

namespace Quark::System {
    constexpr u8          OsVersionMajor = $VERSION_MAJOR;
    constexpr u8          OsVersionMinor = $VERSION_MINOR;
    constexpr const char* OsVersionPatchId = "$VERSION_PATCH";
}
EOF